### ISSUE TITLE
Blocked access tracking

### ISSUE THREAD

**Issue by ccris02** [polkadot-js/phishing#1050]
Would it be possible to add a tracking future into polkadot.js extension to keep account of how many times each website was blocked by polkadot.js extension?

**Comment by jacogr** [comment]
So polkadot-js as a whole doesn't have any databases or servers running anywhere, so there is no endpoint to push to.

In general I'm against all kinds of tracking, even in a case like this where it could be useful. For instance, have no stats on the number of users using things like the apps UI and in the extension explicitly state that there is no tracking or any information sent anywhere.

So yes, we can setup a machine somewhere and then manage the infrastructure and then have some opt-in somewhere in the extension to track, however both these go against "we don't monitor and we don't centralize".

**Comment by ccris02** [comment]
Good points Jaco 🥺. It's cool I'm looking at other ways to get some statistics about scam websites. Thank.
