### ISSUE TITLE
Error with https://stablepool.io/

### ISSUE THREAD

**Issue by FelipeLeivaCortes** [polkadot-js/phishing#1051]
When i try to access this site (https://stablepool.io/) the extension polkadot.js block it

**Comment by dubstard** [comment]
This means that the extension saved you from visiting a known fraudulent website, which is good!
stablepool.io [190.115.18.139] is already dead anyway.
[Mirror](https://urlscan.io/result/610be41c-06bb-4d1c-8e7d-1949dd68b903/)
DDOS GUARD RU is a known provider tied to cyber crime. There are no legit sites there whatsoever, 100% guaranteed!

@jacogr i believe this can be closed.
