### ISSUE TITLE
whitelist-network.com error!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by theeurinworld** [polkadot-js/phishing#1091]
I got this problem while trying to connect to whitelist-network.com

You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.

https://whitelist-network.com/

**Comment by dubstard** [comment]
This was a scam website which is no longer working.

[Mirror](https://urlscan.io/result/01cb53bb-ca99-489c-96ab-3c86a8d61abe/)

When i see the word "kindly" i wanna close my laptop forever
