### ISSUE TITLE
a new scam

### ISSUE THREAD

**Issue by jackesky2** [polkadot-js/phishing#1132]
https://www.exosama.com

**Comment by jacogr** [comment]
Struggling a bit with this one? I have not dove into the community, but at least from a site perspective it seems legit?

**Comment by jackesky2** [comment]
@jacogr let me ask Donnie and his crew. give me a few hours

**Comment by jackesky2** [comment]
> @jacogr let me ask Donnie and his crew. give me a few hours. I left a message on their discord to follow it up

I have spoken to Donnie, he tells me that the three bellow are legit urls,

moonsama.com
exosama.com
battlefornova.com
