### ISSUE TITLE
sorry by mistake this problem facing

### ISSUE THREAD

**Issue by mohitsolankioffically** [polkadot-js/phishing#1322]
please resolve this issue

**Comment by ccris02** [comment]
Little bit more details would be helpful as "sorry by mistake this problem facing" and "please resolve this issue" doesn't really explain what issue are you facing.

**Comment by mohitsolankioffically** [comment]
[image: image.png]i am facing this issue

**Comment by ccris02** [comment]
Sorry, I don't understand your issue. 
Do you have trouble accessing some websites or are you an owner of a site that was blocked?

**Comment by ccris02** [comment]
Sorry to hear that. Your site was tagged as impersonating [https://polkadot.network/](https://polkadot.network/) 

As you can see in the provided images in [PR #1319](https://github.com/polkadot-js/phishing/pull/1319)

**Comment by mohitsolankioffically** [comment]
[image: image.png]how to remove this page

**Comment by mohitsolankioffically** [comment]
i removed all pages from server please remove this page
[image: image.png]

**Comment by dubstard** [comment]
![image](https://user-images.githubusercontent.com/49607867/160222855-df86c4c2-d1db-49c2-a4c3-c76f9a32a988.png)
client hold
![image](https://user-images.githubusercontent.com/49607867/160222874-dfd1e923-aba4-46f9-846d-9cbb23d1b710.png)

**Comment by dubstard** [comment]
> Coinpolkadot.com

Care to explain how the project is related to polkadot
why was there a polkadot logo etc?
