### ISSUE TITLE
New scam url

### ISSUE THREAD

**Issue by jackesky** [polkadot-js/phishing#135]
https://polkadot-promo.info/

**Comment by jackesky** [comment]
Url already posted as scam

**Comment by jacogr** [comment]
They are making a comeback, this morning a new address was detected on that scam - https://github.com/polkadot-js/phishing/pull/134

**Comment by jackesky** [comment]
I have tried several times to email a few of the web-hosting provider a few
of the scam URLS. They seem to be happy to leave many of them up. Often I
fill in a report get given a ticket number then that is it.  I suggest the
threat of legal acton for damages will force the web-host providers to take
down the scams right away.
