### ISSUE TITLE
5DcCqFpFkvDQLsMRabGbki26ducMP6zT2QBaxTmM5aGhhngf

### ISSUE THREAD

**Issue by Poxa142190** [polkadot-js/phishing#145]

**Comment by Poxa142190** [comment]
5DcCqFpFkvDQLsMRabGbki26ducMP6zT2QBaxTmM5aGhhngf

**Comment by jacogr** [comment]
Do you have specific details around this account?

**Comment by Poxa142190** [comment]
Sorry. Sent not there

вт, 2 мар. 2021 г. в 21:20, Jaco Greeff <notifications@github.com>:
