### ISSUE TITLE
improper phishing detection for fleek.co storage api

### ISSUE THREAD

**Issue by cloutprotocol** [polkadot-js/phishing#1472]
when accessing content at this link, polkadot wallet prevented access 
https://storageapi2.fleek.co/

**Comment by jacogr** [comment]
Added in https://github.com/polkadot-js/phishing/pull/1396

Will make a PR to remove it, the malicious path (see the phishing https://urlscan.io/result/09e36954-105e-4520-b557-d801e7d5c4d3/), should not block the domain in this case.
