### ISSUE TITLE
Remove https://emily.ghost.io/ from phishing list

### ISSUE THREAD

**Issue by Nexus2k** [polkadot-js/phishing#1538]
https://emily.ghost.io/ is the actual ghost hosted page for polkadot.network (e.g. the CNAME points to that ghost instance). It therefore doesn't make sense to mark that page as phising site.

**Comment by laboon** [comment]
Indeed, this was a mistake on my part when I filed the original PR - https://github.com/polkadot-js/phishing/pull/1298 . I'll file a PR.

**Comment by laboon** [comment]
PR: https://github.com/polkadot-js/phishing/pull/1539

**Comment by jacogr** [comment]
Closed in linked PR
