### ISSUE TITLE
scam url

### ISSUE THREAD

**Issue by cooldude78** [polkadot-js/phishing#1601]
app.element.io

**Comment by jacogr** [comment]
This is the official Matrix app. (Sadly, like Telegram scammers will send weird URLs as messages, however the app itself is above-board)

**Comment by ical10** [comment]
Although we won't block Matrix app, please share any suspicious link and we'll check it (and ban it accordingly).

**Comment by cooldude78** [comment]
ok no problem here is a new one targeting Exosama on a fake telegram group,

https://defiprotocol.biz/

**Comment by jacogr** [comment]
Closing. (Last url also listed in https://github.com/polkadot-js/phishing/issues/1605)
