### ISSUE TITLE
Incorrectly flagged

### ISSUE THREAD

**Issue by bMuTech** [polkadot-js/phishing#1608]
This website was flagged incorrectly  https://protocoldappsauthen.online

**Comment by ical10** [comment]
which part of this is incorrect?
this is a common phishing kit that we've always found.
![Screen Shot 2022-05-27 at 09 46 57](https://user-images.githubusercontent.com/14356826/170619498-2863401d-0f57-42ce-a0c0-886eff1ebe29.png)
