### ISSUE TITLE
A site is not merging into all.json

### ISSUE THREAD

**Issue by frankywild** [polkadot-js/phishing#1841]
Hello all,

This site "connect.sale-ico.com" was merged into all.json file here #1633 and here #1838 

But I still can't see it on the file. Why is that?

Thanks

**Comment by jacogr** [comment]
It only keeps the top-levels. So you will see that `connect.sale-ico.com` is available here https://polkadot.js.org/phishing/ - but in the all.json it actually drops it - if the top-level matches, the sub-domains are just extra, i.e. it will block `connect.sale-ico.com` as well as `anything.sale-ico.com`.

Either way the phishing extension will block it. Having this slightly cleaned up just makes the list (slightly less) hairy.

I would still recommend listing both sub and tops as they are available - at worst it shows up in the site list (and certainly helps a bit with traceability on the PRs)
