### ISSUE TITLE
posible suplantación en polkadot.js 

### ISSUE THREAD

**Issue by 130213** [polkadot-js/phishing#2116]
Desconozco si me han suplantado la identidad de mis semillas en polkadot.js y en Acala
En discord me han contacctado un chico que dice ser que no es moderador por eso no puedo verlo en el grupo de Acala oficial, que es jefe de equipos técnicos, y solo atienden a personas al azar con algunos problemas criticos y vitales en Acala. Dice ser el Jefe del equipo técnico, que no es moderador ni administrador.
La verdad es que me ha llevado a una página para que conectara mi billetera y esa página pedian las frases semilla. Y como sean un pishing tiene mis frases semilla tanto de Polkadot.js como de Acala. 
El chico responde con el nombre de HUGHES
p.D. : Menuda tarde

**Comment by jacogr** [comment]
Is it possible to log this in English? (I am also not a native speaker, so understand having to communicate in non-mother languages, however in this case cannot quite understand what is logged here)

**Comment by 130213** [comment]
Hello
I do not know if the identity of my seeds has been supplanted in polkadot.js and in Acala
In discord I have been contacted by a boy who claims to be that he is not a moderator, that is why I cannot see him in the official Acala group, who is the head of technical teams, and they only serve random people with some critical and vital problems in Acala. He claims to be the Head of the technical team, who is not a moderator or administrator.
The truth is that he has taken me to a page to connect my wallet and that page asked for the seed phrases. And since they are a phishing, it has my seed phrases from both Polkadot.js and Acala.
The boy responds with the name of HUGHES
PS: what an afternoon

**Comment by jacogr** [comment]
Unfortunately if the seed phrase is compromised, the attacker can get access to all your funds. 

The only thing I can suggest is to transfer out the funds (if they are not locked and not already transferred out). 

If they have been transferred out, the best we can do here is to add the recipient addresses for the funds to the blacklist. (If you can supply the details of the transactions)

Additionally, if you still have the web link for the seed stealer page, we can add that address to a deny list to warn other victims.
