### ISSUE TITLE
Feature SubWallet as a wallet that supports polkadot{.js}/phishing

### ISSUE THREAD

**Issue by RyanDinh8** [polkadot-js/phishing#2136]
SubWallet has added the feature to leveraged phishing websites & addresses database from https://polkadot.js.org/phishing/ to protect users, and we will update the latest version regularly.

- https://github.com/Koniverse/SubWallet-Extension/issues?q=phishing

Please list SubWallet as a wallet that supports polkadot{.js}/phishing on the website: https://polkadot.js.org/phishing/. 
Here is our website: https://subwallet.app/

Thanks a lot!

Ryan from SubWallet.

**Comment by jacogr** [comment]
It would be fastest and simplest just to submit a PR on https://github.com/polkadot-js/phishing/blob/77e1b795a4206f6f669674f9a27e73f7b6305012/index.html#L56

Will mark it and if no PR, will get it it (no promises as to "when")

**Comment by RyanDinh8** [comment]
We will do that. Thank you Jaco.
