### ISSUE TITLE
I cannot find HELP on Polkadot

### ISSUE THREAD

**Issue by bxamberge** [polkadot-js/phishing#219]
I have an account with a small balance and cannot find anyway to quit and get my funds back. My balance was too small to stake with anyone, so it has just sat there for days and days. I cannot find a way to UNbond it; it asks for fees that the Controller account is too small ??? - and I cannot withdraw or send anything ... and I have tried everything I can think of.  THERE IS NO email for help - no way to contact support either ... any help from someone???
- - - crxltd@protonmail.com

**Comment by michalisFr** [comment]
@bxamberge Sorry to hear you couldn't find our contact info. Can you send an email with your address to `support (at) polkadot.network` and we'll help you figure this out.
