### ISSUE TITLE
这个是否是钓鱼网站？

### ISSUE THREAD

**Issue by jianwwpro** [polkadot-js/phishing#2296]
https://manual-syncronisation.ml/fix/?auth=RESOLVE

**Comment by jacogr** [comment]
Thank you for reporting, the URL has been added to the deny list previously.

It is one of those sites that tries to get the mnemonic phrase from the user, e.g 

![image](https://user-images.githubusercontent.com/1424473/191698398-e7dd2b2c-22eb-41d9-b5b0-726afc53e4bc.png)
