### ISSUE TITLE
This is not phishing!

### ISSUE THREAD

**Issue by yeti2020** [polkadot-js/phishing#2314]
I participated in a $starly token sale at Blocto launchpad.
While I trying to claim my vested tokens, why is it displying errors like this?

**Comment by jacogr** [comment]
Please supply the URL so it can be tracked and looked at.

**Comment by yeti2020** [comment]
Here is the URL...
https://starly.io/token

**Comment by jacogr** [comment]
The above URL is not blocked by the phishing list, i.e. it can load without any issues, even with the extension checking against this list -

![image](https://user-images.githubusercontent.com/1424473/192154105-aa29ae26-4e55-4369-b630-38f9f25b40b7.png)

**Comment by frankywild** [comment]
It seems like this is already fixed. Closing it.

**Comment by yeti2020** [comment]
Thanks.
