### ISSUE TITLE
https://lottery.smartnodes.one

### ISSUE THREAD

**Issue by smartnodesvalidators** [polkadot-js/phishing#2315]
We only validate for the Cosmos Network and not Polkadot.  We use the KEPLR extension to ensure users are safe and no fraud.  This is NOT a phishing site or scam in anyway and would request we are removed from the list please.

Please feel free to browse the site and you will see there is no scam here.

Thank you

**Comment by jacogr** [comment]
Not sure if this is in this deny list, however metamask does block it -

![image](https://user-images.githubusercontent.com/1424473/192154154-a9664e9c-b241-4dbd-9b22-c61bff083846.png)

**Comment by thwjanssen89** [comment]
Its also in our deny list. I don't think it belong there however its not even a generic seedstealer. Even if it is a scam (and I am not saying it is) it doesn't target polkadot in any way. So we can safely remove it from our list.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/phishing/pull/2317
