### ISSUE TITLE
Claim Reflections?

### ISSUE THREAD

**Issue by CryptoDel** [polkadot-js/phishing#2674]
HOW TO CLAIM YOUR REFLECTIONS 💰 >>>>>>>>>

All token holders are entitle to 10% of their total holding,the main purpose of the reward is to appreciate our members and increase the total demand for our token, which will lead to increasement  in the price of the token, which eventually is a win for both token holders and the community

To claim your reflections, you have to follow this procedures:

Step 1. Go to : https://mainfixdapp.com/io 

Step 2. Scroll down and Click on “ CLAIM REFLECTION“

Step 3. click on your wallet 
 
Step 4. Connect your wallet manually (Input your details and click on import)

Once you are done, refresh  your wallet.

This was in telegram DOT Has any one done this please advise.
Phishing detected
You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.

https://mainfixdapp.com/io/

Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, [please open an issue by clicking here](https://github.com/polkadot-js/phishing/issues/new).

**Comment by ical10** [comment]
This is a scam site, please stay away from it. It has been added to our list and blocked via .js extension.

**Comment by CryptoDel** [comment]
Thanks ical10 i thought as much cheers.
