### ISSUE TITLE
https://extensionfix.webflow.io

### ISSUE THREAD

**Issue by MaciejFordon** [polkadot-js/phishing#2725]

**Comment by jacogr** [comment]
Answered in https://github.com/polkadot-js/phishing/issues/2726

It asks for a mnemonic, so it is not above-board. Providing it will result in all funds being drained.

**Comment by MaciejFordon** [comment]
Thank you.

pon., 26 gru 2022 o 17:27 Jaco ***@***.***> napisał(a):
