### ISSUE TITLE
Incorrect addition to phishing list

### ISSUE THREAD

**Issue by decentration** [polkadot-js/phishing#2749]
Please remove https://tickets.newfutures.network from phishing list.

The site was built by [decentration](https://decentration.org), a W3F funded entity, trusted also by multiple blockchain communities.

Do you know what caused this going on the list? This would help me not make same mistake. Because talisman and metamask also have the same phishing flag. 

I think it is because the domain does not have a home page, and is only subdomain.

**Comment by jacogr** [comment]
Looking at the site itself, no idea why it was listed in https://github.com/polkadot-js/phishing/pull/2717 (it doesn't ask for a see, simple connect)
