### ISSUE TITLE
Request for additions to all.json

### ISSUE THREAD

**Issue by Nyquist01** [polkadot-js/phishing#2757]
| Site | | |
| ------------- | ------------- | ------------- |
| `https://www.simplcswap.io` |![simple](https://user-images.githubusercontent.com/121832203/210579358-13a43bf3-053d-48db-bd37-63cc959aad4d.jpg)| clicking this ad redirects to simplcswap.io. Looks identical to simpleswap.io
| `simpleswąp.com` | ![simple2](https://user-images.githubusercontent.com/121832203/210580422-9dffb4d1-eb89-4027-b8f3-271c6e6c9bd8.jpg) | Looks identical to simpleswap.io

**Comment by jacogr** [comment]
Will need to be checked, not sure if these are still valid.

**Comment by frankywild** [comment]
Both sites seem to be taken down, I'm going to close this issue.
