### ISSUE TITLE
covo assets disappeared, screen has chnaged

### ISSUE THREAD

**Issue by brainexpert** [polkadot-js/phishing#3269]
I bought and staked 314,000 covo. It was earning rewards, and my screen showed the COVO price, amoutnt staked, my rewards, multiplier, and on the right of that showed my rewards. Below that it showed COVOLP info on th eleft and Escrowed COVO on the right. I can no longer find that page, and the whole app.covo appearance has changed. The same url no longer shows the same thing as it used to. I assume this is the V2 chnges, but on the new app.covo I can't see my assets.

**Comment by frankywild** [comment]
I'm closing this since it has nothing to do with Polkadot.
