### ISSUE TITLE
False Positive discord-accounts.ru

### ISSUE THREAD

**Issue by mmoadvert** [polkadot-js/phishing#3483]
Hello. I am the owner of the website https://discord-accounts.ru/, which has been successfully operating since 2020 and is quite popular.

* 0\90 on Virus Total: https://www.virustotal.com/gui/url/60439b3c1f7eacdf4dc6270192197a5673611409cc3e5beab31f8cafc5d9f231
* We do not claim to be the official discord site, we have our own store of discord accounts.
* We never used Polkadot extension at all. We don't accept this cryptocurrency on our website and don't plan to. Only found out today from a customer that we have a lock here. Our visitor has this extension installed and is not allowed to access our site.

![image](https://github.com/polkadot-js/phishing/assets/75162773/e119f04f-257d-4883-a06a-44a352d82caa)

In this thread I saw that you blocked the site only because it is Russian? Is this really your policy?

https://github.com/polkadot-js/phishing/issues/3286

There is definitely no phishing on the site. I would appreciate checking the site and removing false positives.

**Comment by frankywild** [comment]
> Hello. I am the owner of the website https://discord-accounts.ru/, which has been successfully operating since 2020 and is quite popular.
> 
> * 0\90 on Virus Total: https://www.virustotal.com/gui/url/60439b3c1f7eacdf4dc6270192197a5673611409cc3e5beab31f8cafc5d9f231
> * We do not claim to be the official discord site, we have our own store of discord accounts.
> * We never used Polkadot extension at all. We don't accept this cryptocurrency on our website and don't plan to. Only found out today from a customer that we have a lock here. Our visitor has this extension installed and is not allowed to access our site.
> 
> ![image](https://user-images.githubusercontent.com/75162773/248050639-e119f04f-257d-4883-a06a-44a352d82caa.png)
> 
> In this thread I saw that you blocked the site only because it is Russian? Is this really your policy?
> 
> #3286
> 
> There is definitely no phishing on the site. I would appreciate checking the site and removing false positives.

That site is basically made so people can spam multiple servers with multiple bot accounts. We fight also against that. 

It is not because is Russian. We don't care where it is coming from.

**Comment by mmoadvert** [comment]
> > Привет. Являюсь владельцем сайта https://discord-accounts.ru/ , который успешно работает с 2020 года и достаточно популярен.
> > 
> > * 0\90 по количеству вирусов: https://www.virustotal.com/gui/url/60439b3c1f7eacdf4dc6270192197a5673611409cc3e5beab31f8cafc5d9f231
> > * Мы не претендуем на статус официального сайта дискорда, у нас есть собственный магазин дискорд-аккаунтов.
> > * Мы вообще никогда не использовали расширение Polkadot. Мы не принимаем эту криптовалюту на нашем сайте и не предлагаем. Только сегодня узнал от клиента, что у нас тут замок. Наш посетитель установил это расширение, и ему не разрешен доступ к сайту.
> > 
> > ![изображение](https://user-images.githubusercontent.com/75162773/248050639-e119f04f-257d-4883-a06a-44a352d82caa.png)
> > В этой теме я увидел, что вы заблокировали сайт только потому, что он русский? Это действительно ваша политика?
> > #3286
> > На сайте точно нет рыбалки. Буду признателен за проверку сайта и удаление ложных атак.
> 
> Этот сайт в основном создан для того, чтобы люди могли спамить несколько серверов с широким кругом учетных записей ботов. Мы боремся и против этого.
> 
> Это не потому, что он русский. Нам все равно, откуда это исходит.



> > Hello. I am the owner of the website https://discord-accounts.ru/, which has been successfully operating since 2020 and is quite popular.
> > 
> > * 0\90 on Virus Total: https://www.virustotal.com/gui/url/60439b3c1f7eacdf4dc6270192197a5673611409cc3e5beab31f8cafc5d9f231
> > * We do not claim to be the official discord site, we have our own store of discord accounts.
> > * We never used Polkadot extension at all. We don't accept this cryptocurrency on our website and don't plan to. Only found out today from a customer that we have a lock here. Our visitor has this extension installed and is not allowed to access our site.
> > 
> > ![image](https://user-images.githubusercontent.com/75162773/248050639-e119f04f-257d-4883-a06a-44a352d82caa.png)
> > In this thread I saw that you blocked the site only because it is Russian? Is this really your policy?
> > #3286
> > There is definitely no phishing on the site. I would appreciate checking the site and removing false positives.
> 
> That site is basically made so people can spam multiple servers with multiple bot accounts. We fight also against that.
> 
> It is not because is Russian. We don't care where it is coming from.

The site was created so that users could buy clean Discord accounts for their own purposes, which do not concern us in any way.

You can't claim that accounts are only bought for spam either, as you have no such information. You are only making a supposition, which is not the basis for blocking.

The simplest example. A tool store sells a chainsaw. Someone will use it for its intended purpose and work with wood, and someone will attack a man and saw him in two. So what, are we going to block tool stores now? I hope the elementary logic is clear here, the analogy with our situation.

The site itself does not violate anything, so the label "phishing" is at least misinformation and descreditation.

If you have something against selling social media accounts, you need to block hundreds of thousands of stores all over the world at once, not selectively a specific site.

I hope for your sanity, let's live amicably and not interfere with each other's work.
