### ISSUE TITLE
False Positives on adding Connext Network Bridge URL as a phishing site

### ISSUE THREAD

**Issue by tann9949** [polkadot-js/phishing#3676]
Connext Network is a legit bridge with a creditable company profile. Connext team had been operating as a interoperability protocol for years, and recently they just rebranded from xpollinate to Connext Bridge. This causes their URL to changed to bridge.connext.network. I think this is a misunderstanding to flag Connext domain as a phishing website. 

The PR that mark connext as a phishing website was #3670. I strongly believe this was a mistake.

Additional comment here, what are the criteria for merging the PR? It seems that you have no clear explanation on why you add any specific reason why you blacklist a specific site as a phishing. In the PR #3670, the screenshot evidence was just a window showing that user can use subscan to connect to the site without any explanation why this is consider phishing. Furthermore, the Polkadot.js site doesn't provide a choice for users to access the website like Talisman does.

My concern to the above comment is that without a proper checking on why a site is consider scam, it can lead to many false positives when detecting a phishing site.

**Comment by thwjanssen89** [comment]
The screenshots in the PR aren't for proof that something is a scam but for our own administration they are targetting the polkadot ecosystem.

As for proper checking, we report hundreds of sites each month, sometimes, very rarelly a legit sites comes in. The connext site in specifc was reported by some other third party reported I also check and it honestly did look very scammy to me on first sight and tbh it still does but I did some double checking and it apears to be legit indeed so I removed this one now. 

Btw the arkham one really is a scam. The real one is arkhamintelligence.com. As for your last note in over a year of reporting thousands of scam sites this is just the second times a legit site has been added to the repo by my knowledge. I consider that pretty good.

**Comment by ical10** [comment]
Just to add, since this is also an open-source list, anyone is more than welcome to contribute to report for real scams and even flag false positives (like what you just did). 

We appreciate your report and honestly our response time was quite fast. In other anti-scam filters / wallets, it'd probably take several working days to resolve this situation (vs. what we did in several hours, on the weekend).
