### ISSUE TITLE
Add specific twitter profiles to list?

### ISSUE THREAD

**Issue by NukeManDan** [polkadot-js/phishing#378]
Would it be possible to have the extension warn for specific twitter profiles? 
https://twitter.com/ `KSMStarter` is reported as a scam, as an example

**Comment by jacogr** [comment]
There is no path blocking atm, same for t.me links.

As to the above, they do have various domains -

https://ksmstarter.com/
https://ksmstarter.medium.com/

**Comment by michalisFr** [comment]
KSM starter is like Polkastarter for Kusama. It's called a scam in the context that it has no relation to Kusama. And although this is true, and they may never have, since it's not an outright scam we shouldn't add it to the phishing list.
