### ISSUE TITLE
internal Lido Transfer

### ISSUE THREAD

**Issue by Hegger66** [polkadot-js/phishing#3793]
what happened here ?
0x0ca0a489efd1db2d7d020a26a2f37fc803ff8b630591dd32027a3c1f40ab3fac (transaction Hash)

my staked Ether have been transferred, now I don´t see my funds any more

**Comment by frankywild** [comment]
> what happened here ? 0x0ca0a489efd1db2d7d020a26a2f37fc803ff8b630591dd32027a3c1f40ab3fac (transaction Hash)
> 
> my staked Ether have been transferred, now I don´t see my funds any more

Hello, do you know this is a phishing repo for Polkadot? What does this have to do with it?
