### ISSUE TITLE
Removal Request

### ISSUE THREAD

**Issue by dexdev8** [polkadot-js/phishing#3989]
Hello we have changed wallets configuration and removed subwallets as an option , 
please remove hydrastake.com from the list , thank you

**Comment by frankywild** [comment]
> Hello we have changed wallets configuration and removed subwallets as an option , please remove hydrastake.com from the list , thank you

Hello, why did you remove Subwallet as an option? Your site is legit, isn't it? I've just checked that on your Twitter.

**Comment by frankywild** [comment]
https://github.com/polkadot-js/phishing/pull/3990
