### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by JIBON786** [polkadot-js/phishing#4037]
""You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens ""

i can't understand what is this issue 

pls help  my discord id : jibon786 

my wallet : 0x7a5B2ADe17F5dBa8bb1f83fDbDE66f45558F6ea0

**Comment by frankywild** [comment]
What domain is showing that?

**Comment by ical10** [comment]
Hey @JIBON786 , could you specify which site you're visiting?
