### ISSUE TITLE
Phishing detected

### ISSUE THREAD

**Issue by VasilVR** [polkadot-js/phishing#4099]
Hello team,

We just released our platform -https://node-hub.net/

When I activate your plugin and try to reach it I get this message:

Phishing detected

You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.

https://node-hub.net/

Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, [please open an issue by clicking here](https://github.com/polkadot-js/phishing/issues/new).

Our platform is 100% and I don't believe anyone reported it at all. Anyway, can you please remove it from your list or check what is causing this issue and fix it?

Thanks team!

Greetings,
V

**Comment by gcvinha** [comment]
I need to access https://node-hub.net/ and my Polkadot extension is blocking it.

**Comment by frankywild** [comment]
Could you share more information about that "project" with us? Nothing in that site is working, just the "connect wallet" button.

**Comment by gcvinha** [comment]
Hello Frank.
The project is about the HyperCycle token (HYPC) and is related to the
Cryptopia VC community. The said site give us the possibility to manage our
nodes. They give the power to AI computing and blockchain synergy.

Best regards,
Curty

Em sáb., 16 de dez. de 2023 às 17:22, Frank ***@***.***>
escreveu:

**Comment by frankywild** [comment]
Can you share with us any official site from HyperCycle mentioning your project?

**Comment by VasilVR** [comment]
Hello @frankywild!

This is an article from HyperCycle medium, announcing Cryptopia as the official node distributor:

https://medium.com/hypercycle/official-node-distributor-announcement-cryptopia-group-3c6908797d9d

This is a post from Hypercycle's official X account stating that Cryptopia is building a monitoring platform:

https://x.com/Hypercycle_AI/status/1735400431357218936?s=20

This is Cryptopia's official Discord server. You can join it to read the discussions about the NodeHub platform: 

https://discord.com/invite/cryptopia-group
