### ISSUE TITLE
false flag for pancake swap by polkadot extensions

### ISSUE THREAD

**Issue by pentol86** [polkadot-js/phishing#4115]
i've received false warning from polkadot js on mozilla firefox. it's labeled as " phising" when i try open the website. please fix
![pancake](https://github.com/polkadot-js/phishing/assets/41653075/b28948d9-a6b8-4283-99c1-e47752e282bf)

**Comment by frankywild** [comment]
Done! https://github.com/polkadot-js/phishing/pull/4122
