### ISSUE TITLE
Aptos.pancakeswap Not Open

### ISSUE THREAD

**Issue by bandanaranas** [polkadot-js/phishing#4116]
While I opened this site "https://aptos.pancakeswap.finance/swap" Polkadot js is blocking this site.
![sdfdf](https://github.com/polkadot-js/phishing/assets/87375265/2041a3af-b882-4061-afa9-1c19653bf809)

**Comment by frankywild** [comment]
https://github.com/polkadot-js/phishing/pull/4122
