### ISSUE TITLE
pancakeswap finance website false phishing alert

### ISSUE THREAD

**Issue by talariganesh** [polkadot-js/phishing#4119]
Phishing detected
You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.

https://pancakeswap.finance/swap?chain=bsc

Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, [please open an issue by clicking here](https://github.com/polkadot-js/phishing/issues/new).

**Comment by frankywild** [comment]
https://github.com/polkadot-js/phishing/pull/4122
