### ISSUE TITLE
Site won't open because of phishing

### ISSUE THREAD

**Issue by mpiinvest** [polkadot-js/phishing#4185]
I was sent to this site by the Viction support team to track down my missing tokens.

I can't enter the site because of the phishing warning.

I need to follow their directions to get back my missing TOMO tokens.

**Comment by frankywild** [comment]
> I was sent to this site by the Viction support team to track down my missing tokens.
> 
> I can't enter the site because of the phishing warning.
> 
> I need to follow their directions to get back my missing TOMO tokens.

Can you tell us what that site is? If it is marked as phishing, it is almost 100% malicious, but we can always make mistakes, so please tell us which site you are referring to.
