### ISSUE TITLE
I cant claim my rewards

### ISSUE THREAD

**Issue by younggun2121** [polkadot-js/phishing#4194]
Hi, 
I cant claim my ASTR rewards, it says insufficient transferable balance.
Can anyone help?
Thanks

**Comment by frankywild** [comment]
> Hi, I cant claim my ASTR rewards, it says insufficient transferable balance. Can anyone help? Thanks

Sorry but this is not the place to ask these kind of questions. You should try to ask on Astar's Discord or any other support channel they may have.

**Comment by younggun2121** [comment]
Hi,
Sorry but Astr telegram forum has directed me .
Thanks

9 Oca 2024 Sal 17:28 tarihinde Frank ***@***.***> şunu yazdı:
