### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Brazilec55** [polkadot-js/phishing#4242]
https://api27-collab.land/slugs/evm=J2ZXIiOnsiYWdlIjoiaHR0cHM6Ly9jaGluYS5jb20vdGVzdC8xMjM0NTY3O/?code=fMQHvQEQI4jXybpv8xvlTPczkCksXB

**Comment by frankywild** [comment]
> https://api27-collab.land/slugs/evm=J2ZXIiOnsiYWdlIjoiaHR0cHM6Ly9jaGluYS5jb20vdGVzdC8xMjM0NTY3O/?code=fMQHvQEQI4jXybpv8xvlTPczkCksXB

Hello, that site is a scam and it's already in our repo.
