### ISSUE TITLE
I can't find my project.

### ISSUE THREAD

**Issue by summer1874** [polkadot-js/phishing#4296]
My Repository and Homepage have both changed, but these changes are not reflected in tea. Could you help me identify the issue or manually add it to your database?

NPM URL: https://www.npmjs.com/package/pda-vxe-table
GitHub URL: https://github.com/summer1874/pda-vxe-table

The following cannot be found at all:
NPM URL: https://www.npmjs.com/package/vuepress-theme-tea
GitHub URL: https://github.com/summer1874/vuepress-theme-tea

**Comment by frankywild** [comment]
> My Repository and Homepage have both changed, but these changes are not reflected in tea. Could you help me identify the issue or manually add it to your database?
> 
> NPM URL: https://www.npmjs.com/package/pda-vxe-table GitHub URL: https://github.com/summer1874/pda-vxe-table
> 
> The following cannot be found at all: NPM URL: https://www.npmjs.com/package/vuepress-theme-tea GitHub URL: https://github.com/summer1874/vuepress-theme-tea

Sorry, but what does this have to do with Polkadot?
