### ISSUE TITLE
Dot staking on polkadot-js

### ISSUE THREAD

**Issue by fabrita8** [polkadot-js/phishing#4360]
I staked on https://github.com/polkadot-js, but now cannot recover the DOT coins nor rewards.

Sent a few emails to different supports, but no response

Please advise

Thanks

fabian.g.noronha@gmail.com

**Comment by frankywild** [comment]
> I staked on https://github.com/polkadot-js, but now cannot recover the DOT coins nor rewards.
> 
> Sent a few emails to different supports, but no response
> 
> Please advise
> 
> Thanks
> 
> [fabian.g.noronha@gmail.com](mailto:fabian.g.noronha@gmail.com)

Hello fabrita, this is only for phishing. You can contact the team here https://polkadot.network/contact/ or join our discord channel to get help about your issue https://polkadot-discord.w3f.tools/
