### ISSUE TITLE
Urgent: Remove polkadot.world from phishing list

### ISSUE THREAD

**Issue by sumeetpatel** [polkadot-js/phishing#4445]
Would like the polkadot.world domain removed from the phishing list. We acquired the domain and are launching an app for Consensus 2024 with Distractive and the Parity team using this domain. Can reach out to @exiledracers on twitter or discord if you have any questions on validity or anyone from the Distractive team. Need this approved as soon as possible.

**Comment by frankywild** [comment]
Done
