### ISSUE TITLE
I am not sure if I can register this scam dot address in another location.

### ISSUE THREAD

**Issue by cooldude78** [polkadot-js/phishing#445]
this one 125W1NSHM63kKp1xTrKgUijAMMKKm8kwgydXKno6VNhKs77i

plus 

https://telegra.ph/WELCOME-TO-THE-Polkadot-08-04 
https://link.trustwallet.com/send?coin=354&address=125W1NSHM63kKp1xTrKgUijAMMKKm8kwgydXKno6VNhKs77i

this is from a new telegram group found by Telegram user Danny4dayz.

Good news, Polkadot has lunched partnership giveaway with Coinbase pro. 

Polkadot believes that blockchain and DOT coin will make the world more fair. 

To speed up the process of cryptocurrency mass adoption, We decided to run 5,000,000 DOT Airdrop 

To participate you most have the minimum requirement amount in your wallet. As soon as you participate you will receive your 3x bonus within 4 to 8 minutes. You need a minimum of 50 DOT to participate in the giveaway. 

Send DOT to the contract address bellow 👇👇👇👇

125W1NSHM63kKp1xTrKgUijAMMKKm8kwgydXKno6VNhKs77i

📢Partnership Giveaway 🔉

Rules: you can only participate once

You can use any wallet or exchange to participate.

https://telegra.ph/WELCOME-TO-THE-Polkadot-08-04

**Comment by jacogr** [comment]
Thank you, this is the right place, address has been added in PR https://github.com/polkadot-js/phishing/pull/446
