### ISSUE TITLE
Request for removing "blockchainkeyvault.com" from all.json

### ISSUE THREAD

**Issue by lousydropout** [polkadot-js/phishing#4477]
I recently bought the domain [blockchainkeyvault.com](https://blockchainkeyvault.com) for a password manager project, only to find out that it's being flagged as a phishing site by SubWallet (specifically, the subdomain [app.blockchainkeyvault.com](https://app.blockchainkeyvault.com) is). I'm hoping to get this corrected.

If you'd like to talk, I'm happy to provide additional info. You can contact me either through this issues thread, email (lousydropout@gmail.com), or telegram (https://t.me/lousydropout).

Thanks

**Comment by frankywild** [comment]
> I recently bought the domain [blockchainkeyvault.com](https://blockchainkeyvault.com) for a password manager project, only to find out that it's being flagged as a phishing site by SubWallet (specifically, the subdomain [app.blockchainkeyvault.com](https://app.blockchainkeyvault.com) is). I'm hoping to get this corrected.
> 
> If you'd like to talk, I'm happy to provide additional info. You can contact me either through this issues thread, email ([lousydropout@gmail.com](mailto:lousydropout@gmail.com)), or telegram (https://t.me/lousydropout).
> 
> Thanks

https://github.com/polkadot-js/phishing/pull/4478

**Comment by lousydropout** [comment]
thanks!
