### ISSUE TITLE
Phishing detected

### ISSUE THREAD

**Issue by Andrei08767** [polkadot-js/phishing#4550]
Hello! I can't get to this site.https://manta-front-8ti5w3bew-manta-fullstack.vercel.app/manta/bridge   
You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.
Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, [please open an issue by clicking here](https://github.com/polkadot-js/phishing/issues/new).
help me get to the site

**Comment by frankywild** [comment]
> Hello! I can't get to this site.https://manta-front-8ti5w3bew-manta-fullstack.vercel.app/manta/bridge You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens. Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, [please open an issue by clicking here](https://github.com/polkadot-js/phishing/issues/new). help me get to the site

Why do you want to get to that site? it looks like it's a scam site.
