### ISSUE TITLE
Is https://dapps-chains.com/ safe to use?

### ISSUE THREAD

**Issue by 247earnings** [polkadot-js/phishing#4569]
I am trying to recover a fet.ai wallet.  Using the Other Wallet option to recover ny wallet, I am being asked to input my seed phrase.  While this makes logical sense, T'm a bit apprehensive about disclosing my seed phrase on a strange site.

is it normal to ask for a seed phrase on a 3rd party site?

Thanks,

Rudy

**Comment by ical10** [comment]
Hi @247earnings , any domains in our list is supposedly less than honest, so I would highly recommend not to interact with any of them. Please contact your wallet provider directly to solve your issue.
