### ISSUE TITLE
My website was added to the blocklist 

### ISSUE THREAD

**Issue by KarimJedda** [polkadot-js/phishing#4628]
User @frankywild added my website dottakeout to the blocklist https://github.com/polkadot-js/phishing/pull/4609 and I'd like to understand why?

Project info: https://x.com/KarimJDDA/status/1826212221069701216

**Comment by frankywild** [comment]
> User @frankywild added my website dottakeout to the blocklist #4609 and I'd like to understand why?
> 
> Project info: https://x.com/KarimJDDA/status/1826212221069701216

https://github.com/polkadot-js/phishing/pull/4629

**Comment by KarimJedda** [comment]
Thank you! Any recommendation for me how I can avoid this in the future?
