### ISSUE TITLE
Website flagged incorrectly: anonswap.app

### ISSUE THREAD

**Issue by ZKilion** [polkadot-js/phishing#4660]
Please notice that https://www.anonswap.app/ is being flagged incorrectly and access blocked by Bittensor Chrome Extension (see annex).

The site is clean and the person responsible for it can be contacted at: kelvinjones@outlook.com

![2024-09-13 152108](https://github.com/user-attachments/assets/9298e50a-d953-4801-9c67-ad31bb6b4c0c)

**Comment by frankywild** [comment]
> Please notice that https://www.anonswap.app/ is being flagged incorrectly and access blocked by Bittensor Chrome Extension (see annex).
> 
> The site is clean and the person responsible for it can be contacted at: [kelvinjones@outlook.com](mailto:kelvinjones@outlook.com)
> 
> ![2024-09-13 152108](https://private-user-images.githubusercontent.com/181565661/367510095-9298e50a-d953-4801-9c67-ad31bb6b4c0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTM5MTMsIm5iZiI6MTcyNjM5MzYxMywicGF0aCI6Ii8xODE1NjU2NjEvMzY3NTEwMDk1LTkyOThlNTBhLWQ5NTMtNDgwMS05YzY3LWFkMzFiYjZiNGMwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQwOTQ2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjYxYWVhZWZlMGEzMWQwM2QzYmE0YWU4ZmNkZDdmMTg5M2YyMTdiYjMyZTRmZTY2NDNkYmQ1NDIzMzU3NTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xNC385tuY0iOu083zl48Gwq7e1dC8WGl1nXfxNLtiw8)

Sorry, but we've made some tests and the site is clearly fake and a scam. It will stay like this.
