### ISSUE TITLE
1 previous scam URL and 1 new one and 1 address

### ISSUE THREAD

**Issue by cooldude78** [polkadot-js/phishing#471]
This one bellow needs to be done again as it is showing up. Microsoft have not listed the page as Phishing thanks I think to my report.

https://robonomics-network-xrt.cyberfi-tech-rewards-programs-claims-erc20-token.com/myetherwallet/access-my-wallet/#/input-privatekey-mnemonic-phrase-claim-bonus

also

0x3D87b1618fa930cA3224720610A8B086aa581b49

and

https://moonbeam.presale.fund/

**Comment by jacogr** [comment]
The first site is listed, however the extension seems to have issues (it doesn't sit on this layer, i.e. https://github.com/polkadot-js/phishing/pull/472 does work as expected, so in some way the extension passes something invalid through)

**Comment by crystalin** [comment]
I confirm they are not managed by Moonbeam foundation nor Purestake

**Comment by cooldude78** [comment]
I had a question from a team supporter from Phishfort.

He asks what do you mean by *"it doesn't sit on this layer" *
His also says the following,

*" Text within? Im not sure I follow? Do they mean the json was malformed?"*

*cheers*
*Jack Esky*

**Comment by jacogr** [comment]
See the linked Issue above in the extension - https://github.com/polkadot-js/extension/issues/802
