### ISSUE TITLE
Urgent: Request for removing "destranetwork.io" from io/all.json

### ISSUE THREAD

**Issue by DestraNetwork** [polkadot-js/phishing#4726]
Our unified dApp, hosted on the domain destranetwork.io, has been mistakenly flagged as phishing in this repository. This is our legitimate domain, which can be verified via the 'Get Started' link located in the hero section of our official landing page (destra.network). Please remove this flag at your earliest convenience, as it is affecting our community.

For further verification, we are also willing to confirm the authenticity of destranetwork.io through our official X handle, @destranetwork .

**Comment by frankywild** [comment]
> Our unified dApp, hosted on the domain destranetwork.io, has been mistakenly flagged as phishing in this repository. This is our legitimate domain, which can be verified via the 'Get Started' link located in the hero section of our official landing page (destra.network). Please remove this flag at your earliest convenience, as it is affecting our community.
> 
> For further verification, we are also willing to confirm the authenticity of destranetwork.io through our official X handle, @DestraNetwork .

Done! and sorry for that, it happens rarely.
