### ISSUE TITLE
Can you add a test URL to the block list?

### ISSUE THREAD

**Issue by polkadot-market** [polkadot-js/phishing#4784]
Hello,

Working to update: https://github.com/polkadot-market/phishing

To make it run on the new Reddit Devvit platform so it can be deployed to whichever subreddit needs it.

I need to test it but I don't want to use a known spam domain to test with.

Can we add something like:

https://pretend-bad-site.local

or similar?

Thanks

**Comment by frankywild** [comment]
> Hello,
> 
> Working to update: https://github.com/polkadot-market/phishing
> 
> To make it run on the new Reddit Devvit platform so it can be deployed to whichever subreddit needs it.
> 
> I need to test it but I don't want to use a known spam domain to test with.
> 
> Can we add something like:
> 
> https://pretend-bad-site.local
> 
> or similar?
> 
> Thanks

Sorry, but shouldn't be a real site what is added?

**Comment by exposphere** [comment]
No, imagine you are testing hand grenades, you would probably want a fake hand grenade to test with so it doesn't blow up in your face.

I have to copy a URL to a known bad site onto my clipboard and post it on my test subreddit. That puts me at risk.

Other developers will likely encounter the same thing.

**Comment by polkadot-market** [comment]
A test URL would be useful as it is safer to test with a URL that isn't a known scam link. Both for the person testing and anyone that might encounter a failed test.

It should be a fake site because otherwise it's possible (although incredibly unlikely) we block someone that doesn't deserve to be blocked. Ideally it would be a completely unique URL not encountered elsewhere (or even valid).

**Comment by frankywild** [comment]
> A test URL would be useful as it is safer to test with a URL that isn't a known scam link. Both for the person testing and anyone that might encounter a failed test.
> 
> It should be a fake site because otherwise it's possible (although incredibly unlikely) we block someone that doesn't deserve to be blocked. Ideally it would be a completely unique URL not encountered elsewhere (or even valid).

Done here https://github.com/polkadot-js/phishing/pull/4800

Once someone merge it, you can test it.
