### ISSUE TITLE
Checking if à site is legit or not

### ISSUE THREAD

**Issue by albertrh** [polkadot-js/phishing#4809]
Hi, 
I got this message when connecting to this site (address from CoinGecko). Is it really a scam ?
Thanks
-------------------------------------------
Phishing détecté
You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.

**https://pepeunchained.com/en/dashboard**

Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, [please open an issue by clicking here](https://github.com/polkadot-js/phishing/issues/new).

**Comment by frankywild** [comment]
> ## Hi,
> I got this message when connecting to this site (address from CoinGecko). Is it really a scam ?
> Thanks
> Phishing détecté You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.
> 
> **https://pepeunchained.com/en/dashboard**
> 
> Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, [please open an issue by clicking here](https://github.com/polkadot-js/phishing/issues/new).

Sorry, it was flagged by mistake. https://github.com/polkadot-js/phishing/pull/4811
