### ISSUE TITLE
report of malicious site

### ISSUE THREAD

**Issue by 0350d3a3a3ea40e3baa4aa6b34f71cfc** [polkadot-js/phishing#4822]
Hey there I would like to report this site  | Reason: crypto drainer

https://node-repair-hub.pages.dev

![398738845-232ac083-c59f-4b0e-be8d-fbdfdd7bc7a9](https://github.com/user-attachments/assets/a862f5e2-9192-4682-840e-b5b781e55b92)

**Comment by frankywild** [comment]
> Hey there I would like to report this site | Reason: crypto drainer
> 
> https://node-repair-hub.pages.dev
> 
> ![398738845-232ac083-c59f-4b0e-be8d-fbdfdd7bc7a9](https://private-user-images.githubusercontent.com/155373060/398742097-a862f5e2-9192-4682-840e-b5b781e55b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMzkwOTUsIm5iZiI6MTczNTIzODc5NSwicGF0aCI6Ii8xNTUzNzMwNjAvMzk4NzQyMDk3LWE4NjJmNWUyLTkxOTItNDY4Mi04NDBlLWI1Yjc4MWU1NWI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxODQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWI3MTJjYjJlZDM0NTliZTZhNmNhYzU4YzQ2ZGYzNGNiOTAwZGY1MzgyNzFhYTFhYmVkMjQ2N2U4NTRmODg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i-JUklC1-P3Zte6ieX-UVzFBZLy_Q0y6upvJWzxSleM)

Thanks! Added here https://github.com/polkadot-js/phishing/pull/4823
