### ISSUE TITLE
new mars token.

### ISSUE THREAD

**Issue by cooldude78** [polkadot-js/phishing#487]
https://marsecosystem.com/home

this website is registered in the same place as all the scam Polkadot, Moonbeam sites have been. They added between 500 to 50k in members in their Telegram over the past 24hrs, inlcuing myself.

**Comment by cooldude78** [comment]
Reference 1
https://www.whois.com/whois/marsecosystem.com

Reference 2 
https://www.whois.com/whois/wallectconnectapps.com

Reference 3 
https://www.whois.com/whois/wallectconnectapps.com

Reference 4
https://www.whois.com/whois/polkarstarter.com

All Registered through Namecheap, Reykjavik, Captial Region, in IS

**Comment by cooldude78** [comment]
and this is another one different to mars

https://v2.mainwallerdapps.com

**Comment by jacogr** [comment]
Notr sure about Mars, couldn't find anything Polkadot-ecosystem related on it.

**Comment by cooldude78** [comment]
no problem about Mars. we do however got this new Moonbeam scam going on, 

https://moonbeam.ink
