### ISSUE TITLE
airdrop

### ISSUE THREAD

**Issue by umutacar00** [polkadot-js/phishing#652]
I used the platform for its good. But didnt receive any airdrops.

**Comment by ccris02** [comment]
There is no Airdrops in Polkadot network. What website have you used to request the Airdrops?

**Comment by Gfxbyboss** [comment]
Copy and paste in your trust wallet .. we are already listed on CoinMarketCaps.

0xe302bf71b1f6f3024e7642f9c824ac86b58436a0

Add to your trust wallet then join there community here on telegram ....the coin  main exchange is already listed on CoinMarketCaps..

More like 
Binance and there BNB coin

Pancake swap and cake coin

Moonpot and pot coin

Trust wallet and trust coin

Ok-Blockchain exchange  and OKB coin

The coin current worth 23$ in CoinMarketCaps.. just ask me the community so you claim more of it

Ask me for the community link 

Guys simply join the community and then add invite just 5 people to claim there own

That qualifies you for a complete 1500 OKB which is the withdrawal limit you can do more and get more

We are lossing nothing here so I don't see why we shouldn't go for  it.... think about it.. what's the worst that can happen ?

OK-BLOCKCHAIN AIRDROP💠
The cryptocurrency exchange

with the most options

OKB offers a fully customizable Bitcoin and cryptocurrency exchange for traders at every level
https://t.me/OKBLOCKCHAIN
