### ISSUE TITLE
KSMstarter showing up even after being removed

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/phishing#654]
KSMstarter shows up under https://polkadot.js.org/phishing/ even after it has been removed from the phishing list

**Comment by caizhiyuanrise** [comment]
maybe it is a scam regardless,,.. one member of KSM saying all good with it does not justify it. getting removed?

**Comment by michalisFr** [comment]
@caizhiyuanrise The scope of this repo is to list sites that are clearly scams or phishing, like giveaways or seed stealers, in order to warn users visiting them (if the use the Polkadot extension). KSMstarter doesn't fall in this category, which is why it was removed from the repo [here](https://github.com/polkadot-js/phishing/pull/569#issue-1020852514).

This issue addressed the fact that it was still showing up on the site, even after being removed from the repo. As may have been the case with other entries too
