### ISSUE TITLE
Phishing/Scam Addresses supplied by last years scam victom, Zhang CL who got scammed and lost 10571 dot

### ISSUE THREAD

**Issue by jackesky** [polkadot-js/phishing#69]
bellow are the list of new addresses that Zhang CL posted on the Main Polkadot page back in September 2020  after sending his dot to a scam address. It is believed that these dot were then sent to other addresses. 

We would like these address to be included on the list of records.

 
1461Dsvr9GmkRjUkdJcYGP6HFygwQeZcspc6W5QgJVAT59yt
 
13xuoAwwqfZuyAsRuUBasa8AhjdqzRbdyS3m52Lu6oCpFQRv

1X3M7sGA1Nbgd8Qh45uqdQMPNFXSHbWnvPp6CkQ9Ttp46dQ
 
13afnZRWDqmaRapMg6URQkDEnoxuVzHUCYo2v61dXaKHdgBB
 
1X3M7sGA1Nbgd8Qh45uqdQMPNFXSHbWnvPp6CkQ9Ttp46dQ
 
14QsifyV7XyEDay8C862PNLRngid2AGZmtCwz1K88x5gpf58

the transacton hash which started the whole mess is, https://polkascan.io/polkadot/transaction/0xa47ca656821e912fa7d53b77ca1117751734ae7e8feb29a4a829eefdd22d65d0

**Comment by jackesky** [comment]
1exaAg2VJRQbyUBAeXcktChCAqjVP9TUxF3zo23R2T6EGdE

14gWkqi6J3U4mcRTCi7yy824S2GepSNqpM4xNjLTCzGQpCst

**Comment by jacogr** [comment]
Thanks! Do you have a link to the original post? (The reason for asking is just for categorization, eg. see https://github.com/polkadot-js/phishing/blob/master/address.json - for instance not all are sites, the last is for a telegra.ph link)

**Comment by jackesky** [comment]
I do have these links. Can I forward these to you in dm on Telegram?  Do you have an telegram account username?
