### ISSUE TITLE
Phishing scam site bitz.country.

### ISSUE THREAD

**Issue by justinphamnz** [polkadot-js/phishing#690]
Hello @jacogr,

Hope you had a great weekend. 

We found a phishing scam site bitz.country to pretend bit.country, they are trying to scam the ecosystem and community. 
Bitz.country has no association with bit.country, please add them to phishing site.

PR created here #689 

Thanks team for your consideration. 

Justin from Bit.Country.

**Comment by jacogr** [comment]
Closed in #689
