### ISSUE TITLE
Many scammers on discord

### ISSUE THREAD

**Issue by heartium** [polkadot-js/phishing#706]
Didn't realize so many scammers on official channels of token teams on discord. Many of these scammers use usernames--such as Help Desk, SupportDsk(R), moderator that make them sound more legit.. 

One website I'd like to add to the phishing list myself is "apps.securessync.info"

By hanging out on discord, you probably get many phishing sites.

**Comment by jacogr** [comment]
There are a number of users that make regular PRs that monitor -

- Riot
- Discord
- New domain registrations (!!!)

For myself, cannot spend more time on socila media, I won't get work done. so it a community effort to keep up to date.

If you find scammers, do report them - or even better, make a PR.
