### ISSUE TITLE
Expose all.json on IPFS (via phishing.dotapps.io)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/phishing#8]

**Comment by sexpo** [comment]
Here is the first list of Scam Urls found up until January 24th 2021

https://polkadots.network/block.html
http://polkadots.network
http://polkadot-live.online
http://polkadotlive.network

https://walletsynchronization.com/unlock/mnemonic  ( this one has been taking huge amounts of cryptos off lots of people) whois.net are not taking this one down

cheers jackesky

**Comment by jackesky** [comment]
https://polkadot-airdrop.org/
https://polkadot.company/
https://cutt.ly/fjYqA9P
http://polkadot-live.online/index.html
https://polkadots.network/
https://bit.ly/2L60w13

**Comment by jacogr** [comment]
@jackesky The missing ones (not already in the list) was added as part of https://github.com/polkadot-js/phishing/pull/60
