### ISSUE TITLE
Fishing Google Chrome extension

### ISSUE THREAD

**Issue by RomeroYang** [polkadot-js/phishing#813]
see the issue https://github.com/polkawallet-io/app/issues/98, reported by polkawallet user.

**Comment by kopax-polyconseil** [comment]
I lost 1 DOT that Polkadot forced me to leave on that fished account, is there a way to get it back somehow?

**Comment by Shamandoc** [comment]
The same add-on is still in the Chrome Store and I fell into the same trap. I tried to enter polkadot js words and thought it was polkadot js plugin. There are some seed sales and vomit pre-sales that I participate in this wallet. These have not been credited to my account yet. If I open a new wallet, what will happen to the projects that are not transferred to my account? How come this extension is still in the Chrome Store?

**Comment by kopax-polyconseil** [comment]
Good question, and why polkadot-js is not replying ? I want my DOT back, but I also expect polkadot to take action not to let people like you get scam. 24 days and still no action as been taken

**Comment by kopax-polyconseil** [comment]
For those who want their 1 dot back after saving their found from this hacker : https://support.polkadot.network/support/solutions/articles/65000169248-error-balances-transferkeepalive-

**Comment by jacogr** [comment]
There is absolutely nothing that "polkadot-js", aka me, can do here. 

Don't expect miracles, I'm a single person - so what I did, hopefully alongside everybody else, was to report the extension, on Google. Apart from that, here we are dealing with a faceless store on the web, so reports is the only thing that can be done. At some point Google will take action.

**Comment by kopax-polyconseil** [comment]
After mailing support at polkadot.network, they were able to send me a fraction of dot so I got able to send my remaining DOT, now I got no lost, I recommend every person in my situation to do the same. 

An action have been taken for the fishing extension and now polkadot is waiting for the removal of it.

**Comment by kopax-polyconseil** [comment]
This should be kept open for tracking until the extension is removed from chrome extension store.
