### ISSUE TITLE
localpolkadot domains

### ISSUE THREAD

**Issue by gmaron721** [polkadot-js/phishing#831]
"localpolkadot.com",
  "localpolkadot.ru",
  "localpolkadots.com",
  "localpolkadots.ru",
  
 my domains are not phishing.
I am not doing anything illegal.
Please remove them from the all.json list

**Comment by dubstard** [comment]
The user claims they are "not doing anything illegal."

What exactly are they doing then?
What is the purpose of those domains?
Why are they hosted on a dirty IP related to various scams?

**Comment by gmaron721** [comment]
Firstly, the domain is hosted by a regular host. Since when did it become dirty?

Secondly, even if nothing is posted there now, it does not mean that it will not be later.

Even bonus cybersquatting is not a scam.

I think you are being unfair to me.

And why did you even decide to make a blacklist. Make a whitelist.

Отправлено из мобильного клиента ProtonMail

-------- Исходное сообщение --------
В 21 янв. 2022 г., 21:02, Mich написано:

**Comment by dubstard** [comment]
The blacklist entries have been removed.

Please don't act as being threated unfair.

Hosting your "harmless domains" on a known IP address related to cyber crime hurts the reputation of your "harmless" domains.


Why did you ignore my questions
```
What exactly are they doing then?
What is the purpose of those domains?

```
![image](https://user-images.githubusercontent.com/49607867/150594593-486cc8e5-5ab0-447e-8264-1f028ab97d81.png)

![image](https://user-images.githubusercontent.com/49607867/150594625-301e621b-44b9-4afb-a361-2e3935080222.png)
![image](https://user-images.githubusercontent.com/49607867/150594649-0c7bc165-cfd4-4b4e-a485-e3fdf8dcfd6a.png)

You come here with an account especially created to beg for removal and acting all innocent.
Sprint have multiple SBL entries at any given time.

This particular IP address has been detected as phishing by myself personally.

**Comment by gmaron721** [comment]
beget.com is a Russian hoster. You probably know that when you order only hosting and not a dedicated server. then many sites of different people work on the same server.

scammers are everywhere. I think that it is wrong to look simply by IP.

On these domains, I wanted to make a p2p service. But it turned out to be more difficult than I thought.
Now I am negotiating with LocalCryptos.
But it is possible that I will make a simple information portal.

Отправлено из мобильного клиента ProtonMail

-------- Исходное сообщение --------
В 22 янв. 2022 г., 0:20, Mich написано:

**Comment by dubstard** [comment]
Thanks for the explanation.
Beget have bad ratio good /to bad sites, due to "regional peculiarities" (safeharbor for cyber crime)

**Comment by dubstard** [comment]
The same person keeps registering more of those.
`https://localpolkadot.online`

**Comment by dubstard** [comment]
I will get in touch with LocalCryptos who are a customer of PF and ask to validate those claims, as i suspect those have nothing to do with neither polkadot nor LocalCryptos
