### ISSUE TITLE
now i have recover my account  

### ISSUE THREAD

**Issue by loveyout269** [polkadot-js/phishing#917]
Nobi — 01/04/2022
🏆 Congratulations, REACH MAN & SONS 🏆

You have been randomly selected in the Giveaway among users of Blockchain Monster Hunt Official. We are a fast-growing crypto project which offers the best conditions to hold or trade your Crypto!

To attract new users we have made a giveaway with 200 prizes cost almost 25 BTC!

🔥 You WON: 0.194 BTC + bonus! 🔥

How to receive your reward:
1⃣ Register an account: https://bit-temp.com/
2⃣ Click on the "Ref. codes" tab and activate your promo code:
3⃣ Done!
i was lost my phone now i recover my Discord id & saw prize how can i clime my prize please help me ?

**Comment by jacogr** [comment]
It is a known phishing scam, i.e. it gets blocked by this list.
