### ISSUE TITLE
goboardup.com/wp-admin is my legit website. 

### ISSUE THREAD

**Issue by lubinwangus** [polkadot-js/phishing#979]
Could you take out this warning?  It is my website.   I cannot access it right now

**Comment by jacogr** [comment]
The domain is blocked due to the following sub-domain - 

extension-metamask.com.goboardup.com

Once a scam appears on a sub-domain, the root domain is also blocked.

**Comment by dubstard** [comment]
![image](https://user-images.githubusercontent.com/49607867/150628983-376fa964-8620-4c0c-8043-0508548d842b.png)
