### ISSUE TITLE
Telegram invites added?

### ISSUE THREAD

**Issue by NukeManDan** [polkadot-js/phishing#99]
https://t . me/polkadotofficialtelegram is a scam.

This redirects in app, but sometimes they are found in browsers. Should we add know telegram groups to the block list?

https://t.me/<BAD GROUP> and the like

**Comment by jacogr** [comment]
Currently not. The checks are actually per domain only. 

Apart from that anything that redirects into an app won’t give enough time for the extension to actual block. So link shorteners that “go somewhere” can only block the destination. 

So we can add these under a new section (like “denyLink”) to at least start tracking them, but atm it would need some thinking on stuff like the extension to see how to actually block these.

**Comment by jackesky** [comment]
3 scam telegram groups have been taken down past 12 hrs Feb15 and 16th 2021. I think it was done by the scammers as opposed to the people at Telegram as the groups were not scam listed but the scam admin profiles that had been on them.

I expect all three will pop up within a few months. one has 23k members, 1 had 1500 members, the other one had 1900 members.

**Comment by Vraethnyr** [comment]
Seems that there is one primary group going right now with quite a force behind them - or one very determined, very greedy individual/duo in a likewise position. Looking into what they have setup (the group I suspect to be the primary group) they are not so much organized as they are bold. They are leaving a lot to be discovered easily - I am guessing they don't think anyone is going to stop them. Not going to leave anything here until I get something concrete, but I am sleuthing my way around for shits n giggles. I'll dump everything I find on IPFS if it amounts to anything truly worthwhile.

**Comment by jackesky** [comment]
Can you DM me about what your saying on Telegram, thank you.

**Comment by Wraethnyr** [comment]
> Can you DM me about what your saying on Telegram, thank you.

I am not aware of a way to DM on Github. Where would you like me to contact you?
If you are on element: @vraethnyr:matrix.org
